### ISSUE TITLE
thumbActiveClassName is still in the DOM after dragging

### ISSUE THREAD

**Issue by hinok** [zillow/react-slider#166]
### Edit

I fixed the issue on my side by using good old css `:active` for my thumbs like:

```css
.my-handle:active {
    box-shadow:
        0 0 0 14px rgba($color-secondary, 0.4),
        0 3px 12px -3px rgba($color-dark-jungle, 0.36);
}
```

```javascript
  renderThumb = (thumbProps, thumbState) => {
    return (
      <div {...thumbProps} key={thumbState.index} className="my-handle">
          {thumbState.valueNow}
      </div>
    );
  };
```

I assume that the difference between `v0.11.2` and `v1.0.3` is caused by a11y improvements.
I close the issue.

---

Hey,
One of the previous versions of react-slider had functionality that after dragging thumbs with the mouse, `active` class (`thumbActiveClassName`) was always removed from the DOM.

Now this class is still at the DOM after dragging. Look at the gif below.

![video-smaller](https://user-images.githubusercontent.com/1313605/75043123-d1965b00-54bf-11ea-805d-91fbd7fbf453.gif)

### Demo

`v1.0.3`: https://codesandbox.io/s/frosty-gauss-rxjk6
`v0.11.2` https://codesandbox.io/s/lingering-dawn-1xtsu

You can easily see that in `v1.0.3` gray background is still there after dragging.
