### ISSUE TITLE
Default style looks bad.

### ISSUE THREAD

**Issue by jakehm** [zillow/react-slider#91]
Why can't the slider come with a default style that doesn't look so bad?  So if I wanted to use the component, I wouldn't have to do the styling myself.

**Comment by shin-monkey** [comment]
Maybe we all could share the styling made for this.

**Comment by alexisross** [comment]
Hi, here an example (but the counter disappear for me, anyway not sure it's a problem of css):
![react-slider-orange-pill](https://cloud.githubusercontent.com/assets/17320998/20772817/56bd1c18-b74f-11e6-9499-e6af82ab0230.png)

```css
.horizontal-slider {
    width: 100%;
    height: 42px;
    border: 2px solid #ff7200;
    border-radius: 25px;
}

.handle {
    font-size: 0.9em;
    text-align: center;
    background-color: #ff7200;
    color: yellow;
    cursor: pointer;
    top: 02px;
    width: 34px;
    height: 34px;
    border-radius: 20px;
    border: 2px solid white;
}

.handle.active {
    border: 5px solid white;
}

.bar {
    position: relative;
    background: #ff7200;
}

.bar.bar-1 {
    background: #a5a5a5;
}

.horizontal-slider .bar {
    top: 6px;
    height: 26px;
    border-radius: 16px;
    margin: 0 6px;
}
```
